inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('acerca_de_mi/', views.acerca_de_mi, name='acerca_de_mi'),
    path('primer-vista/', views.primer_vista, name='primer-vista'),
    path('fecha-actual/', views.fecha_actual, name='fecha-actual'),
    path('saludar/', views.saludar, name='saludar'),
    path('bienvenida/<str:nombre>/<str:apellido>', views.bienvenida, name='bienvenida'),  
   
    path('autos/', views.ListarAutos.as_view(), name='listar_autos'),
    path('autos/crear/', views.CrearAuto.as_view(), name='crear_auto'),
    path('autos/eliminar/<int:pk>/', views.EliminarAuto.as_view(), name='eliminar_auto'),
    path('autos/modificar/<int:pk>/', views.ModificarAuto.as_view(), name='modificar_auto'),
    path('autos/<int:pk>/', views.MostrarAuto.as_view(), name='mostrar_auto'),
]

miprimerdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('inicio.urls')),
    path('usuario/', include('usuario.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.urls import path
from usuario import views
from django.contrib.auth.views import LogoutView

app_name = 'usuario'

urlpatterns = [
    path('login/', views.login, name ='login'),
    path('logout/', LogoutView.as_view(template_name='usuario/logout.html'), name ='logout'),
    path('registro/', views.registrarse, name ='registrarse'),
    path('perfil/editar/', views.edicion_perfil, name ='editar_perfil'),
    path('perfil/editar/password/', views.ModificarPass.as_view(), name ='modificar_pass')
]

inicio/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.db import models


class Auto(models.Model):
    nombre = models.CharField(max_length=20)
    marca = models.CharField(max_length=20)
    descripcion = RichTextField(null=True)
    fecha_fabricacion = models.DateField()
    imagen = models.ImageField(null=True, blank=True, upload_to='imagenes/')
    
    def __str__(self):
        return f"Auto: {self.nombre} - Marca: {self.marca}"

usuario/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class InfoExtra(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatares', null=True, blank=True)

inicio/views.py
from typing import Any, Dict
from django.http import HttpResponse
from datetime import datetime
from django.template import Template, Context, loader
from inicio.models import Auto
from django.shortcuts import render, redirect
from inicio.form import CrearAutoFormulario, BuscarAutoFormulario, ModificarAutoFormulario
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


@login_required
def acerca_de_mi(request):
    
    segundos = datetime.now().second
    diccionario = {
        'mensaje': 'Mi nombre de Anabella Bertola,soy alumna de CoderHouse, tengo 28 años y vivo en Rosario.Esta es una pagina informativa a traves de listado de autos alta gama de distintas marcas y modelos, donde podran ver mas informacion de la descripcion',
    }
    
    return render(request, 'inicio/acerca_de_mi.html', diccionario)


def inicio(request):
 return render(request, 'inicio/inicio.html')

def primer_vista(request):
    return HttpResponse('<h1>Soy la primer vista</h1>')

def fecha_actual(request):
    fecha = datetime.now()
    return HttpResponse(f'<h1>Fecha actual: {fecha}</h1>')

def saludar(request):
    return HttpResponse('Bienvenido/a!!!')

def bienvenida(request, nombre, apellido):
    return HttpResponse(f'Bienvenido/a {nombre.title()} {apellido.title()}!!!')


class CrearAuto(CreateView):
    model = Auto
    template_name = 'inicio/CBV/crear_auto_CBV.html'
    fields = ['nombre', 'marca', 'descripcion', 'fecha_fabricacion', 'imagen']
    success_url = reverse_lazy('inicio:listar_autos')
    
class ListarAutos(ListView):
    model = Auto
    template_name = "inicio/CBV/listar_autos_CBV.html"
    context_object_name = 'autos'
    
    def get_queryset(self):
        listado_de_autos = []
        formulario = BuscarAutoFormulario(self.request.GET)
        if formulario.is_valid():
            nombre_a_buscar = formulario.cleaned_data['nombre']
            listado_de_autos = Auto.objects.filter(nombre__icontains=nombre_a_buscar)
        return listado_de_autos
    

    
    
    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)   
        contexto['formulario'] = BuscarAutoFormulario()
        return contexto
    
    
class ModificarAuto(LoginRequiredMixin, UpdateView):
    model = Auto
    template_name = "inicio/CBV/modificar_auto_CBV.html"
    fields = ['nombre', 'marca', 'descripcion', 'fecha_fabricacion', 'imagen']
    success_url = reverse_lazy('inicio:listar_autos')
      
class EliminarAuto(LoginRequiredMixin, DeleteView):
    model = Auto
    template_name = "inicio/CBV/eliminar_auto_CBV.html"
    success_url = reverse_lazy('inicio:listar_autos')

class MostrarAuto(DetailView):
    model = Auto
    template_name = "inicio/CBV/mostrar_auto_CBV.html"
    

    
    

usuario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import authenticate, login as django_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from usuario.form import MiFormularioDeCreacionDeUsuario, MiFormularioDeEdicionDeDatosDeUsuario
from django.urls import reverse_lazy
from usuario.models import InfoExtra


def login(request):
    
    if request.method == 'POST':
        formulario = AuthenticationForm(request, data=request.POST)
        if formulario.is_valid():
            usuario = formulario.cleaned_data['username']
            contraseña = formulario.cleaned_data['password']
            
            user = authenticate(username=usuario, password=contraseña)
            
            django_login(request, user)
            
            InfoExtra.objects.get_or_create(user=user)
            
            return redirect('inicio:inicio')
        else:
            return render(request, 'usuario/login.html', {'formulario': formulario})
    
    
    formulario = AuthenticationForm
    return render(request, 'usuario/login.html', {'formulario': formulario})


def registrarse(request):
    
    if request.method == 'POST':
        formulario = MiFormularioDeCreacionDeUsuario(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect('usuario:login')
        else:
            return render(request, 'usuario/registro.html', {'formulario': formulario})
    
    formulario = MiFormularioDeCreacionDeUsuario()
    return render(request, 'usuario/registro.html', {'formulario': formulario})

@login_required
def edicion_perfil(request):
    info_extra_user = request.user.infoextra
    if request.method == 'POST':
        formulario = MiFormularioDeEdicionDeDatosDeUsuario(request.POST, request.FILES, instance=request.user)
        if formulario.is_valid():
            
            avatar = formulario.cleaned_data.get('avatar')
            if avatar:
                info_extra_user.avatar = avatar
                info_extra_user.save()
            
            
            formulario.save()
            return redirect('inicio:inicio')
    else:
        formulario = MiFormularioDeEdicionDeDatosDeUsuario(initial={'avatar': info_extra_user.avatar}, instance=request.user)
    
    return render(request, 'usuario/edicion_perfil.html', {'formulario': formulario})

class ModificarPass(LoginRequiredMixin, PasswordChangeView):
    template_name = 'usuario/modificar_pass.html'
    success_url = reverse_lazy('usuario:editar_perfil')

inicio/templates/inicio/CBV/crear_auto_CBV.html
{% extends 'base.html' %}

{% block title_head %}
<title>Crear Auto</title>
{% endblock title_head %}

{% block h1_header %}
Crear Auto
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'inicio:crear_auto' %} method="POST" enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
        {{form}}
        {{form.media}}
    </table>

    <button>Crear</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/CBV/crear_perro_CBV.html
{% extends 'base.html' %}

{% block title_head %}
<title>Crear Perro</title>
{% endblock title_head %}

{% block h1_header %}
Crear Perro
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'inicio:crear_perro' %} method="POST">
    {% csrf_token %}
    <table>
        {{form}}
        {{form.media}}
    </table>

    <button>Crear</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/CBV/eliminar_auto_CBV.html
{% extends 'base.html' %}

{% block title_head %}
<title>Eliminar Auto</title>
{% endblock title_head %}

{% block h1_header %}
Eliminar Auto
{% endblock h1_header %}

{% block contenido %}
<form action= {% url 'inicio:eliminar_auto' auto.id %} method="POST">
    {% csrf_token %}
    <p>Confirma el borrado de {{auto}}</p>
    <button>Confirmar</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/CBV/eliminar_perro_CBV.html
{% extends 'base.html' %}

{% block title_head %}
<title>Eliminar Perro</title>
{% endblock title_head %}

{% block h1_header %}
Eliminar Perro
{% endblock h1_header %}

{% block contenido %}
<form action= {% url 'inicio:eliminar_perro' perro.id %} method="POST">
    {% csrf_token %}
    <p>Confirma el borrado de {{perro}}</p>
    <button>Confirmar</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/CBV/listar_autos_CBV.html
{% extends 'base.html' %}

{% block title_head %}
<title>Autos</title>
{% endblock title_head %}

{% block h1_header %}
Listado de Autos
{% endblock h1_header %}

{% block contenido %}
<button>
    <a class="navbar-brand" href= {% url 'inicio:crear_auto' %}>Crear auto</a>
</button>
<form action="" method="get">
    {{formulario}}
    <button>Buscar</button>
</form>

{% if autos %}
{% for auto in autos %}
<li>
    {{auto}}
    <a href={% url 'inicio:mostrar_auto' auto.id%}>Ver mas</a>
    <a href={% url 'inicio:modificar_auto' auto.id%}>Modificar</a>
    <a href={% url 'inicio:eliminar_auto' auto.id%}>Eliminar</a>
</li>
{% endfor %}
{% else %}
<p>No se encontraron datos cargados.</p>
{% endif %}
{% endblock contenido %}

inicio/templates/inicio/CBV/modificar_auto_CBV.html
{% extends 'base.html' %}

{% block title_head %}
<title>Crear Auto</title>
{% endblock title_head %}

{% block h1_header %}
Crear Auto
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'inicio:modificar_auto' %}"" method="POST" enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
        {{form}}
        {{form.media}}
    </table>

    <button>Crear</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/CBV/modificar_perro_CBV.html
{% extends 'base.html' %}

{% block title_head %}
<title>Crear Perro</title>
{% endblock title_head %}

{% block h1_header %}
Crear Perro
{% endblock h1_header %}

{% block contenido %}
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{form}}
        {{form.media}}
    </table>

    <button>Crear</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/CBV/mostrar_auto_CBV.html
{% extends 'base.html' %}

{% block title_head %}
<title>Auto</title>
{% endblock title_head %}

{% block h1_header %}
{{auto.nombre}}
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'inicio:mostrar_auto' auto.id %} method="POST" enctype='multipart/form-data'>
<li>Marca: {{auto.marca}}</li>
<li>Descripcion: {{auto.descripcion | safe}}</li>
<li>Fecha de fabricacion: {{auto.fecha_fabricacion}}</li>
{% if auto.imagen%}
<li><img src = {{auto.imagen.url}} alt ="iamgen del auto"></li>
{% endif %}

{% endblock contenido %}

inicio/templates/inicio/CBV/mostrar_perro_CBV.html
{% extends 'base.html' %}

{% block title_head %}
<title>Perro</title>
{% endblock title_head %}

{% block h1_header %}
{{perro.nombre}}
{% endblock h1_header %}

{% block contenido %}
<li>Edad: {{perro.edad}}</li>
<li>Descripcion: {{perro.descripcion | safe}}</li>
{% endblock contenido %}

inicio/templates/inicio/acerca_de_mi.html
{% extends 'base.html' %}

{% block title_head %}
<title>Acerca de mi</title>
{% endblock title_head %}

{% block h1_header %}
Anabella Bertola
{% endblock h1_header %}

{% block contenido %}
<p>{{mensaje}}</p>

{% endblock contenido %}

inicio/templates/inicio/crear_auto.html
{% extends 'base.html' %}

{% block title_head %}
<title>Autos</title>
{% endblock title_head %}

{% block h1_header %}
Listado de Autos
{% endblock h1_header %}

{% block contenido %}
<button>
    <a class="navbar-brand" href= {% url 'inicio:crear_auto' %}>Crear auto</a>
</button>
<form action="" method="get">
    {{formulario}}
    <button>Buscar</button>
</form>
{% if autos %}
{% for auto in autos %}
<li>
    {{auto}}
    <a href={% url 'inicio:eliminar_auto' auto.id %}>Eliminar</a>
    <a href={% url 'inicio:modificar_auto' auto.id %}>Modificar</a>
</li>
{% endfor %}
{% else %}
<p>No se encontraron datos cargados.</p>
{% endif %}
{% endblock contenido %}
    


 

inicio/templates/inicio/inicio.html
{% extends 'base.html' %}

{% block title_head %}
<title>Inicio</title>
{% endblock title_head %}

{% block h1_header %}
Inicio
{% endblock h1_header %}

{% block contenido %}

{% endblock contenido %}

inicio/templates/inicio/listar_autos.html
{% extends 'base.html' %}

{% block title_head %}
<title>Autos</title>
{% endblock title_head %}

{% block h1_header %}
Listado de Autos
{% endblock h1_header %}

{% block contenido %}
<button>
    <a class="navbar-brand" href= {% url 'inicio:crear_auto' %}>Crear auto</a>
</button>
<form action="" method="get">
    {{formulario}}
    <button>Buscar</button>
</form>
{% if autos %}
{% for auto in autos %}
<li>
    {{auto}}
    <a href={% url 'inicio:eliminar_auto' auto.id%}>Eliminar</a>
    <a href={% url 'inicio:modificar_auto' auto.id%}>Modificar</a>
</li>
{% endfor %}
{% else %}
<p>No se encontraron datos cargados.</p>
{% endif %}
{% endblock contenido %}

inicio/templates/inicio/modificar_auto.html
{% extends 'base.html' %}

{% block title_head %}
<title>Modificar Auto</title>
{% endblock title_head %}

{% block h1_header %}
Modificar Auto
{% endblock h1_header %}

{% block contenido %}
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Modificar</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/modificar_perro.html
{% extends 'base.html' %}

{% block title_head %}
<title>Modificar Perro</title>
{% endblock title_head %}

{% block h1_header %}
Modificar Perro
{% endblock h1_header %}

{% block contenido %}
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Modificar</button>
</form>
{% endblock contenido %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="Anabella Bertola" />
        {% block title_head %}
        <title>Template Base</title>
        {% endblock title_head %}
    
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href= {% url 'inicio:inicio' %}>Inicio</a>
                <a class="navbar-brand" href= {% url 'inicio:acerca_de_mi' %}>Acerca de mi</a>
                <a class="navbar-brand" href= {% url 'inicio:listar_autos' %}>Autos</a>
                {% if request.user.is_authenticated %}
                {% if request.user.infoextra.avatar %}
                <img src={{request.user.infoextra.avatar.url}} alt="" height='40px'>
                {% endif %}
                <a class="navbar-brand" href={% url 'usuario:editar_perfil' %}>{{request.user.username}}</a>
                <a class="btn btn-secondary" href={% url 'usuario:logout' %}>Logout</a>
                {% else %}
                <a class="btn btn-primary" href={% url 'usuario:login' %}>Login</a>
                <a class="btn btn-primary" href={% url 'usuario:registrarse' %}>Registrarse</a>
                {% endif %}
            </div>
        </nav>

        {% block header %}
        <!--Masthead-->
        <header class ="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">
                                {% block h1_header %}
                                Nuestra web intermedia de Django-Coderhouse
                                {% endblock h1_header %}
                            </h1>  
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock header %}
  
        {% block contenido %}
        <p>Soy el template padre!</p>
        {% endblock contenido %}

        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                    <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                    <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
    </html>
    

usuario/templates/usuario/edicion_perfil.html
{% extends 'base.html' %}

{% block title_head %}
<title>Edicion perfil</title>
{% endblock title_head %}

{% block h1_header %}
Editar perfil
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:editar_perfil' %} method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
    {{formulario}}
    </table>
    <button>Guardar cambios</button>
    <button type='button'><a class="navbar-brand" href={% url 'usuario:modificar_pass' %}>Cambiar contraseña</a></button>
</form> 
{% endblock contenido %}

usuario/templates/usuario/login.html
{% extends 'base.html' %}

{% block title_head %}
<title>Login</title>
{% endblock title_head %}

{% block h1_header %}
Login
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:login' %} method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>

    <button>Login</button>
</form>
{% endblock contenido %}

usuario/templates/usuario/logout.html
{% extends 'base.html' %}

{% block title_head %}
<title>Logout</title>
{% endblock title_head %}

{% block h1_header %}
Te deslogueaste con exito!
{% endblock h1_header %}

{% block contenido %}
{% endblock contenido %}

usuario/templates/usuario/modificar_pass.html
{% extends 'base.html' %}

{% block title_head %}
<title>Modificar pass</title>
{% endblock title_head %}

{% block h1_header %}
Modificar pass
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:modificar_pass' %} method="post">
    {% csrf_token %}
    <table>
    {{form}}
    </table>
    <button>Modificar  pass</button>
</form> 
{% endblock contenido %}

usuario/templates/usuario/registro.html
{% extends 'base.html' %}

{% block title_head %}
<title>Regitrarse</title>
{% endblock title_head %}

{% block h1_header %}
Registro
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:registrarse' %} method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>

    <button>Registrar</button>
</form>
{% endblock contenido %}